services:
  - name: backend-service
    type: web
    env: python
    plan: free
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && uvicorn main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: SECRET_KEY
        value: YOUR_SECRET_KEY_HERE
      - key: MONGODB_URI
        value: YOUR_MONGODB_URI_HERE
      - key: DB_NAME
        value: LDA
      - key: OPENAI_API_KEY
        value: YOUR_OPENAI_API_KEY_HERE
      - key: SMTP_USER
        value: YOUR_SMTP_USER_HERE
      - key: SMTP_PASS
        value: YOUR_SMTP_PASS_HERE

  - name: frontend-service
    type: static
    buildCommand: "cd frontend && npm install && npm run build"
    publishPath: "frontend/dist"
    envVars:
      - key: VITE_API_URL
        value: "https://backend-service.onrender.com"
