services:
  - name: backend-service
    type: web
    env: python
    plan: free
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && uvicorn main:app --host 0.0.0.0 --port 8000"

  - name: frontend-service
    type: static
    buildCommand: "cd frontend && npm install && npm run build"
    publishPath: "frontend/dist"
